#ifndef INCLUDED_CONFIG_H
#define INCLUDED_CONFIG_H


#define MAX_ID_LEN (256)

#define DEBUG (1)

#define MAX_ARG_COUNT  (64)
#define MAX_NODE_COUNT (MAX_ARG_COUNT * 1024)

#define MAX_JOB_COUNT (16)
#define MAX_SCOPER_COUNT (16)


#endif  // INCLUDED_CONFIG_H